STDOUT.sync = true

desc "Imports lettings data from csv's generated by previous system."
task :patch => :environment do |_task, args|
  include Logging
  Rake::Task['patch_clients'].invoke
  Rake::Task['patch_properties'].invoke
  Rake::Task['patch_address2'].invoke
  Rake::Task['patch_acc_info'].invoke
  Rake::Task['patch_acc_items'].invoke
end

