# Drop, Create, Migrate, Test Prepare and then populate the development
# Note: db:reset mirrors much of the calls but also db:seed which I didn't want.
# https://gist.github.com/nithinbekal/3423153

STDOUT.sync = true

namespace :db do

  desc "Imports lettings data from csv's generated by previous system."
  task import: [
    'environment',
    'db:truncate_all',   # Stripped out for now but when in parellell with live system. nope
    'import:clients',
    'import:properties'
  ]

end