# Drop, Create, Migrate, Test Prepare and then populate the development
# Note: db:reset mirrors much of the calls but also db:seed which I didn't want.
# https://gist.github.com/nithinbekal/3423153

STDOUT.sync = true

namespace :db do

  desc "Imports lettings data from csv's generated by previous system."
  task :import, [:range, :test] => :environment do |task, args|
    args.with_defaults(range: '1..8000', test: '')

    human_ref_range = Rangify.from_str(args.range).to_s

    # Stripped out for now but when in parellel with live system. nope
    Rake::Task['db:truncate_all'].execute
    Rake::Task['import:users'].invoke(args.test)
    Rake::Task['import:clients'].execute
    Rake::Task['import:properties'].invoke(human_ref_range)
    Rake::Task['import:billing_profiles'].invoke(human_ref_range)
    Rake::Task['import:charges'].invoke(human_ref_range)
    Rake::Task['import:accounts'].invoke(human_ref_range)
    Rake::Task['import:update_charges'].invoke
  end
end