####
#
# Credit
#
# Generated by payments and linked to a debit. The credit offsets
# a debit charged to a property account.
#
#
# A payment is applied to one property account. When being applied
# it finds unpaid debits and generates a matching credit.
# The credits get set during the payments controller #create action.
#
####
#
class Credit < ActiveRecord::Base
  belongs_to :payment
  belongs_to :account
  belongs_to :charge
  belongs_to :debit

  validates :charge_id, :on_date, presence: true
  validates :amount, amount: true
  validates :amount, numericality:
                     { less_than_or_equal_to: 100_000 }

  after_initialize do
    self.on_date = default_on_date if on_date.blank?
    @spent = amount
  end

  def clear_up
    self.mark_for_destruction if amount.nil? || amount.round(2) == 0
  end

  def charge_type
    charge_obj.charge_type
  end

  private

  def spent
    @spent || 0
  end

  def charge_obj
    charge
  end

  def default_on_date
    Date.current
  end
end
