STDOUT.sync = true

namespace :db do
  desc "Imports lettings data from csv's generated by previous system."
  task stage: :environment do |_task, _args|
    include Logging
    logger.info 'db:stage:clients'
    Rake::Task['db:stage:clients'].invoke
    logger.info 'db:stage:properties'
    Rake::Task['db:stage:properties'].invoke
    logger.info 'db:stage:address2'
    Rake::Task['db:stage:address2'].invoke
    logger.info 'db:stage:acc_info'
    Rake::Task['db:stage:acc_info'].invoke
    logger.info 'db:stage:acc_items'
    Rake::Task['db:stage:acc_items'].invoke
  end
end
