STDOUT.sync = true

namespace :db do
  desc "Imports lettings data from csv's generated by previous system."
  task stage: :environment do |_task, _args|
    include Logging
    Rake::Task['db:stage:clients'].invoke
    Rake::Task['db:stage:properties'].invoke
    Rake::Task['db:stage:address2'].invoke
    Rake::Task['db:stage:acc_info'].invoke
    Rake::Task['db:stage:acc_items'].invoke
  end
end